// All the possible mutations for the application

// Init mutations
export const ADD_SEASON_DATA = 'ADD_SEASON_DATA'
export const SET_SEASON_DATA_URLS = 'SET_SEASON_DATA_URLS'
export const SET_HISTORY = 'SET_HISTORY'
export const SET_METADATA = 'SET_METADATA'
export const SET_TIMECHART = 'SET_TIMECHART'
export const SET_CHOROPLETH = 'SET_CHOROPLETH'
export const SET_DISTRIBUTIONCHART = 'SET_DISTRIBUTIONCHART'

export const SET_BRAND_LOGO = 'SET_BRAND_LOGO'

// weeks module
export const UPDATE_SELECTED_WEEK = 'UPDATE_SELECTED_WEEK'

// switch module
export const UPDATE_SELECTED_REGION = 'UPDATE_SELECTED_REGION'
export const UPDATE_SELECTED_SEASON = 'UPDATE_SELECTED_SEASON'
export const TOGGLE_CHOROPLETH_RELATIVE = 'TOGGLE_CHOROPLETH_RELATIVE'
export const DISPLAY_TIMECHART = 'DISPLAY_TIMECHART'
export const DISPLAY_DISTRIBUTIONCHART = 'DISPLAY_DISTRIBUTIONCHART'
export const SET_SEASON_LOADING = 'SET_SEASON_LOADING'

// intro module
export const INCREMENT_INTRO_POINTER = 'INCREMENT_INTRO_POINTER'
export const DECREMENT_INTRO_POINTER = 'DECREMENT_INTRO_POINTER'
export const RESET_INTRO_POINTER = 'RESET_INTRO_POINTER'
export const HIDE_INTRO = 'HIDE_INTRO'
export const SHOW_INTRO = 'SHOW_INTRO'
export const APPEND_INTRO_ITEM = 'APPEND_INTRO_ITEM'
