// All the possible mutations for the application

// Init mutations
export const SET_TIMECHART = 'SET_TIMECHART'
export const SET_CHOROPLETH = 'SET_CHOROPLETH'
export const SET_DISTRIBUTIONCHART = 'SET_DISTRIBUTIONCHART'

// weeks module
export const UPDATE_SELECTED_WEEK = 'UPDATE_SELECTED_WEEK'

// switch module
export const UPDATE_SELECTED_REGION = 'UPDATE_SELECTED_REGION'
export const UPDATE_SELECTED_SEASON = 'UPDATE_SELECTED_SEASON'
export const TOGGLE_CHOROPLETH_RELATIVE = 'TOGGLE_CHOROPLETH_RELATIVE'
export const DISPLAY_TIMECHART = 'DISPLAY_TIMECHART'
export const DISPLAY_DISTRIBUTIONCHART = 'DISPLAY_DISTRIBUTIONCHART'

// intro module
export const INCREMENT_INTRO_POINTER = 'INCREMENT_INTRO_POINTER'
export const DECREMENT_INTRO_POINTER = 'DECREMENT_INTRO_POINTER'
export const RESET_INTRO_POINTER = 'RESET_INTRO_POINTER'
export const HIDE_INTRO = 'HIDE_INTRO'
export const SHOW_INTRO = 'SHOW_INTRO'
export const APPEND_INTRO_ITEM = 'APPEND_INTRO_ITEM'
